# Generated by Django 5.1.6 on 2025-09-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baraa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ner', models.CharField(max_length=100)),
                ('une', models.DecimalField(decimal_places=2, max_digits=10)),
                ('too', models.IntegerField()),
            ],
            options={
                'db_table': 'baraa_tbl',
            },
        ),
    ]
